package com.integrasolusi.pusda.sisda.repository;

/**
 * Programmer   : pancara
 * Date         : 6/22/11
 * Time         : 5:04 PM
 */
public enum BlobDataType {
    DOKUMENTASI_HEADLINE,
    DOKUMENTASI_PHOTO,

    REPOSITORY_PHOTO,

    NEWS_PHOTO,

    PUBLICATION_PICTURE,
    PUBLICATION_ATTACHMENT,

    AGENDA_THUMB,
    BOOK,
    SLIDE,
    LINK,

    POTENSI_SDA,
    POTENSI_SDA_DOCUMENT,

    REGULATION,
    PERSON,
    MAP,

    PROJECT,
    SDA_BENDUNGAN_THUMB,

    PATTERN_AND_PLAN_SDA,

    SDA_SUNGAI,
    SDA_SUNGAI_SUMMARY,

    SDA_BENDUNG,
    SDA_BENDUNG_SUMMARY,

    SDA_HIDROLOGI_CURAH_HUJAN,
    SDA_HIDROLOGI_POS_CH,

    SDA_HIDROLOGI_TMA,
    SDA_HIDROLOGI_POS_TMA,

    SDA_HIDROLOGI_KUALITAS_AIR,

    SDA_HIDROLOGI_SEBARAN_POS,

    SDA_HIDROLOGI_KLIMATOLOGI,
    SDA_HIDROLOGI_POS_KLIMATOLOGI,

    SDA_SABO_DAM_MAP_SUNGAI,
    SDA_SABO_DAM,

    SDA_DAS,

    SDA_DI_TYPE,
    SDA_DI_DI,
    SDA_DI_DATA,

    
    SDA_BANJIR,
    SDA_DAERAH_RAWAN_BANJIR,

    SDA_KEKERINGAN,
    SDA_AIR_TANAH,

    TKPSDA_ACTIVITY_DOCUMENT,
    //    TKPSDA_MEETING_RESULT,
    TKPSDA_MISC_DOCUMENT,
    TKPSDA_EVENT_PICTURE,
//    TKPSDA_DOKUMENTASI_PHOTO,

    LEAFLET_THUMB,
    LEAFLET,

    STRUKTUR_ORGANISASI,

    PROGRESS_PEKERJAAN,

    PRESENTATION_MODULE;

}
